//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKCameraEvent {
  IKUSB_HOTPLUG_EVENT_DEVICE_ARRIVED = (1 << 0),
  IKUSB_HOTPLUG_EVENT_DEVICE_LEFT = (1 << 1),
  IKUSB_EVENT_DEVICE_UPSIDE = (1 << 2),
  IKUSB_MIRRORFLAG_CHECK_ERROR = (1 << 3)
}
