//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKCameraUpdated : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKCameraUpdated(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKCameraUpdated obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IKCameraUpdated obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IKCameraUpdated() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_IKCameraUpdated(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IKFrame frame {
    set {
      dllmainPINVOKE.IKCameraUpdated_frame_set(swigCPtr, IKFrame.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKCameraUpdated_frame_get(swigCPtr);
      IKFrame ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKFrame(cPtr, false);
      return ret;
    } 
  }

  public bool mirrorFlag {
    set {
      dllmainPINVOKE.IKCameraUpdated_mirrorFlag_set(swigCPtr, value);
    } 
    get {
      bool ret = dllmainPINVOKE.IKCameraUpdated_mirrorFlag_get(swigCPtr);
      return ret;
    } 
  }

  public IKCameraEvent _event {
    set {
      dllmainPINVOKE.IKCameraUpdated__event_set(swigCPtr, (int)value);
    } 
    get {
      IKCameraEvent ret = (IKCameraEvent)dllmainPINVOKE.IKCameraUpdated__event_get(swigCPtr);
      return ret;
    } 
  }

  public int deviceType {
    set {
      dllmainPINVOKE.IKCameraUpdated_deviceType_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKCameraUpdated_deviceType_get(swigCPtr);
      return ret;
    } 
  }

  public IKLIGHTMODE lightMode {
    set {
      dllmainPINVOKE.IKCameraUpdated_lightMode_set(swigCPtr, (int)value);
    } 
    get {
      IKLIGHTMODE ret = (IKLIGHTMODE)dllmainPINVOKE.IKCameraUpdated_lightMode_get(swigCPtr);
      return ret;
    } 
  }

  public string deviceSN {
    set {
      dllmainPINVOKE.IKCameraUpdated_deviceSN_set(swigCPtr, value);
    } 
    get {
      string ret = dllmainPINVOKE.IKCameraUpdated_deviceSN_get(swigCPtr);
      return ret;
    } 
  }

  public int deviceSNLen {
    set {
      dllmainPINVOKE.IKCameraUpdated_deviceSNLen_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKCameraUpdated_deviceSNLen_get(swigCPtr);
      return ret;
    } 
  }

  public string deviceTypeString {
    set {
      dllmainPINVOKE.IKCameraUpdated_deviceTypeString_set(swigCPtr, value);
    } 
    get {
      string ret = dllmainPINVOKE.IKCameraUpdated_deviceTypeString_get(swigCPtr);
      return ret;
    } 
  }

  public int deviceTypeStringLen {
    set {
      dllmainPINVOKE.IKCameraUpdated_deviceTypeStringLen_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKCameraUpdated_deviceTypeStringLen_get(swigCPtr);
      return ret;
    } 
  }

  public IKCameraUpdated() : this(dllmainPINVOKE.new_IKCameraUpdated(), true) {
  }

}
