//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKConfigInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKConfigInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKConfigInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IKConfigInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IKConfigInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_IKConfigInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IKEnrollIdentMode mode {
    set {
      dllmainPINVOKE.IKConfigInfo_mode_set(swigCPtr, (int)value);
    } 
    get {
      IKEnrollIdentMode ret = (IKEnrollIdentMode)dllmainPINVOKE.IKConfigInfo_mode_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisMode irisMode {
    set {
      dllmainPINVOKE.IKConfigInfo_irisMode_set(swigCPtr, (int)value);
    } 
    get {
      IKIrisMode ret = (IKIrisMode)dllmainPINVOKE.IKConfigInfo_irisMode_get(swigCPtr);
      return ret;
    } 
  }

  public bool irisEnrollIsEnforce {
    set {
      dllmainPINVOKE.IKConfigInfo_irisEnrollIsEnforce_set(swigCPtr, value);
    } 
    get {
      bool ret = dllmainPINVOKE.IKConfigInfo_irisEnrollIsEnforce_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisWorkMode irisWorkMode {
    set {
      dllmainPINVOKE.IKConfigInfo_irisWorkMode_set(swigCPtr, (int)value);
    } 
    get {
      IKIrisWorkMode ret = (IKIrisWorkMode)dllmainPINVOKE.IKConfigInfo_irisWorkMode_get(swigCPtr);
      return ret;
    } 
  }

  public int irisCount {
    set {
      dllmainPINVOKE.IKConfigInfo_irisCount_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKConfigInfo_irisCount_get(swigCPtr);
      return ret;
    } 
  }

  public int faceCount {
    set {
      dllmainPINVOKE.IKConfigInfo_faceCount_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKConfigInfo_faceCount_get(swigCPtr);
      return ret;
    } 
  }

  public int overTime {
    set {
      dllmainPINVOKE.IKConfigInfo_overTime_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKConfigInfo_overTime_get(swigCPtr);
      return ret;
    } 
  }

  public IKConfigInfo() : this(dllmainPINVOKE.new_IKConfigInfo(), true) {
  }

}
