//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKCOMPONENTTYPE {
  IKCOMPONENT_InfraredLamp = 0,
  IKCOMPONENT_FillLight = 1,
  IKCOMPONENT_OUTPUTRGB = 2,
  IKCOMPONENT_IRISDIVECE_SN = 3,
  IKCOMPONENT_FACEDIVECE_SN = 4,
  IKCOMPONENT_PTZ_CALIBRATION = 5,
  IKCOMPONENT_PTZ_HOMING = 6,
  IKCOMPONENT_PTZ_TEST = 7
}
