//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKDebugInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKDebugInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKDebugInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IKDebugInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IKDebugInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_IKDebugInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IKIrisAndFaceDataValidFlag dataValidFlag {
    set {
      dllmainPINVOKE.IKDebugInfo_dataValidFlag_set(swigCPtr, (int)value);
    } 
    get {
      IKIrisAndFaceDataValidFlag ret = (IKIrisAndFaceDataValidFlag)dllmainPINVOKE.IKDebugInfo_dataValidFlag_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisDebugInfo irisDebugInfo {
    set {
      dllmainPINVOKE.IKDebugInfo_irisDebugInfo_set(swigCPtr, IKIrisDebugInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKDebugInfo_irisDebugInfo_get(swigCPtr);
      IKIrisDebugInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKIrisDebugInfo(cPtr, false);
      return ret;
    } 
  }

  public IKFaceDebugInfo faceDebugInfo {
    set {
      dllmainPINVOKE.IKDebugInfo_faceDebugInfo_set(swigCPtr, IKFaceDebugInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKDebugInfo_faceDebugInfo_get(swigCPtr);
      IKFaceDebugInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKFaceDebugInfo(cPtr, false);
      return ret;
    } 
  }

  public IKDebugInfo() : this(dllmainPINVOKE.new_IKDebugInfo(), true) {
  }

}
