//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKEnrollIdentResultFlag {
  IKEnrRecIrisFaceFailed = -3,
  IKEnrRecFaceFailed = -2,
  IKEnrRecIrisFailed = -1,
  IKEnrRecUnknown = 0,
  IKEnrRecIrisSuccess = 1,
  IKEnrRecFaceSuccess = 2,
  IKEnrRecIrisFaceSuccess = 3
}
