//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKFaceIdentOutputStruct : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKFaceIdentOutputStruct(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKFaceIdentOutputStruct obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IKFaceIdentOutputStruct obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IKFaceIdentOutputStruct() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_IKFaceIdentOutputStruct(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int identResult {
    set {
      dllmainPINVOKE.IKFaceIdentOutputStruct_identResult_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.IKFaceIdentOutputStruct_identResult_get(swigCPtr);
      return ret;
    } 
  }

  public IKFaceMatchOutput matchResult {
    set {
      dllmainPINVOKE.IKFaceIdentOutputStruct_matchResult_set(swigCPtr, IKFaceMatchOutput.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKFaceIdentOutputStruct_matchResult_get(swigCPtr);
      IKFaceMatchOutput ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKFaceMatchOutput(cPtr, false);
      return ret;
    } 
  }

  public IKFaceProcessedResult resultInfo {
    set {
      dllmainPINVOKE.IKFaceIdentOutputStruct_resultInfo_set(swigCPtr, IKFaceProcessedResult.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKFaceIdentOutputStruct_resultInfo_get(swigCPtr);
      IKFaceProcessedResult ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKFaceProcessedResult(cPtr, false);
      return ret;
    } 
  }

  public IKFaceIdentOutputStruct() : this(dllmainPINVOKE.new_IKFaceIdentOutputStruct(), true) {
  }

}
