//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKFaceWorkMode {
  IKFace_WorkMode_Enroll = 0,
  IKFace_WorkMode_Iden = 1,
  IKFace_WorkMode_Idle = -1
}
