//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKFaceUIUEMsgID {
  IKFaceUIUE_MsgID_SUITABLE = 0,
  IKFaceUIUE_MsgID_Detect_MultipleFace = IKFace_Err_BASE-3501,
  IKFaceUIUE_MsgID_Detect_NoFace = IKFace_Err_BASE-3502,
  IKFaceUIUE_MsgID_IDLE_CLEAR = IKFace_Err_BASE-3503,
  IKFaceUIUE_MsgID_IMAGE_Invalid = IKFace_Err_BASE-3504,
  IKFaceUIUE_MsgID_IMAGE_BLUE = IKFace_Err_BASE-3505,
  IKFaceUIUE_MsgID_IMAGE_OVERMOVE = IKFace_Err_BASE-3506,
  IKFaceUIUE_MsgID_ATTACK = IKFace_Err_BASE-3507,
  IKFaceUIUE_MsgID_Invalid_Im_Size = IKFace_Err_BASE-3508,
  IKFaceUIUE_MsgID_Bad_Pos_Move_Left = IKFace_Err_BASE-3509,
  IKFaceUIUE_MsgID_Bad_Pos_Move_Right = IKFace_Err_BASE-3510,
  IKFaceUIUE_MsgID_Bad_Pos_Move_Up = IKFace_Err_BASE-3511,
  IKFaceUIUE_MsgID_Bad_Pos_Move_Down = IKFace_Err_BASE-3512,
  IKFaceUIUE_MsgID_Pos_Move_CLOSE = IKFace_Err_BASE-3513,
  IKFaceUIUE_MsgID_Bad_Pos_Move_FAR = IKFace_Err_BASE-3514,
  IKFaceUIUE_MsgID_Quality_Face_Invalid = IKFace_Err_BASE-3515,
  IKFaceUIUE_MsgID_Quality_Angle_Fail = IKFace_Err_BASE-3517,
  IKFaceUIUE_MsgID_AlignedDepthFace_Fail = IKFace_Err_BASE-3518,
  IKFaceUIUE_MsgID_DepthDetect_Fail = IKFace_Err_BASE-3519,
  IKFaceUIUE_MsgID_DepthSelect_Fail = IKFace_Err_BASE-3520,
  IKFaceUIUE_MsgID_LiveDetect_Fail = IKFace_Err_BASE-3521,
  IKFaceUIUE_MsgID_LiveScore_Fail = IKFace_Err_BASE-3522,
  IKFaceUIUE_MsgID_INVALID = CBDEFAULTVALUE
}
