//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKFrameFormat {
  IK_Frame_Format_YUV = 0,
  IK_Frame_Format_YUYV = 1,
  IK_Frame_Format_YUV20SP = 2,
  IK_Frame_Format_BGRA = 3,
  IK_Frame_Format_BGR = 4,
  IK_Frame_Format_RGBA = 5,
  IK_Frame_Format_RGB = 6,
  IK_Frame_Format_RGB565 = 7,
  IK_Frame_Format_RAW = 8,
  IK_Frame_Format_NV21 = 9,
  IK_Frame_Format_MJPEG = 10,
  IK_Frame_Format_Gray_8 = 11,
  IK_Frame_Format_Gray_16 = 12,
  IK_Frame_Format_DEPTH = 1024,
  IK_Frame_Formate_Unknown = 9999
}
