//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKFrameType {
  IK_Frame_Light = 0,
  IK_Frame_Dark,
  IK_Frame_Depth,
  IK_Frame_IR,
  IK_Frame_IRIS,
  IK_Frame_IRIS_VGA_L,
  IK_Frame_IRIS_VGA_R,
  IK_Frame_IRIS_VGA_LR,
  IK_Frame_Unknown = 9999
}
