//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKIrisProcessedResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKIrisProcessedResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKIrisProcessedResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IKIrisProcessedResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IKIrisProcessedResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_IKIrisProcessedResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IKIrisMode irisMode {
    set {
      dllmainPINVOKE.IKIrisProcessedResult_irisMode_set(swigCPtr, (int)value);
    } 
    get {
      IKIrisMode ret = (IKIrisMode)dllmainPINVOKE.IKIrisProcessedResult_irisMode_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisResultFlag flag {
    set {
      dllmainPINVOKE.IKIrisProcessedResult_flag_set(swigCPtr, (int)value);
    } 
    get {
      IKIrisResultFlag ret = (IKIrisResultFlag)dllmainPINVOKE.IKIrisProcessedResult_flag_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisInfo irisInfo {
    set {
      dllmainPINVOKE.IKIrisProcessedResult_irisInfo_set(swigCPtr, IKIrisInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKIrisProcessedResult_irisInfo_get(swigCPtr);
      IKIrisInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKIrisInfo(cPtr, false);
      return ret;
    } 
  }

  public IKIrisProcessedResult() : this(dllmainPINVOKE.new_IKIrisProcessedResult(), true) {
  }

}
