//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKIrisUIUEMsgID {
  IKIrisUIUE_MsgID_SUITABLE = 0,
  IKIrisUIUE_MsgID_EYE_NOT_FOUND = IKIris_Err_BASE-2501,
  IKIrisUIUE_MsgID_EYE_MOVE_CLOSE = IKIris_Err_BASE-2502,
  IKIrisUIUE_MsgID_EYE_MOVE_FAR = IKIris_Err_BASE-2503,
  IKIrisUIUE_MsgID_EYE_MOVE_UP = IKIris_Err_BASE-2504,
  IKIrisUIUE_MsgID_EYE_MOVE_DOWN = IKIris_Err_BASE-2505,
  IKIrisUIUE_MsgID_EYE_MOVE_LEFT = IKIris_Err_BASE-2506,
  IKIrisUIUE_MsgID_EYE_MOVE_RIGHT = IKIris_Err_BASE-2507,
  IKIrisUIUE_MsgID_MOTION_BLUR = IKIris_Err_BASE-2508,
  IKIrisUIUE_MsgID_FOCUS_BLUR = IKIris_Err_BASE-2509,
  IKIrisUIUE_MsgID_BAD_EYE_OPENNESS = IKIris_Err_BASE-2510,
  IKIrisUIUE_MsgID_EXPOSURE_UNDER = IKIris_Err_BASE-2512,
  IKIrisUIUE_MsgID_EXPOSURE_OVER = IKIris_Err_BASE-2513,
  IKIrisUIUE_MsgID_WITH_GLASS = IKIris_Err_BASE-2514,
  IKIrisUIUE_MsgID_IMAGE_Invalid = IKIris_Err_BASE-2515,
  IKIrisUIUE_MsgID_ATTACK = IKIris_Err_BASE-2516,
  IKIrisUIUE_MsgID_TRACEID_ERROR = IKIris_Err_BASE-2517,
  IKIrisUIUE_MsgID_IDLE_CLEAR = IKIris_Err_BASE-2518,
  IKIrisUIUE_MsgID_FAKE = IKIris_Err_BASE-2519,
  IKIrisUIUE_MsgID_BP = IKIris_Err_BASE-2520,
  IKIrisUIUE_MsgID_OFFANGLE = IKIris_Err_BASE-2521,
  IKIrisUIUE_MsgID_INVALID = CBDEFAULTVALUE
}
