//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKIrisResultFlag {
  IKIrisEnrRecBothFailed = -3,
  IKIrisEnrRecRightFailed = -2,
  IKIrisEnrRecLeftFailed = -1,
  IKIrisEnrRecUnknown = 0,
  IKIrisEnrRecLeftSuccess = 1,
  IKIrisEnrRecRightSuccess = 2,
  IKIrisEnrRecBothSuccess = 3
}
