//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKIrisAndFaceDataValidFlag {
  DataNone = 0,
  IrisDataValid = 1,
  FaceDataValid = 2
}
