//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKLIGHTMODE {
  MODE_DEGUALT = 0,
  MODE_ASYNFREQUENT = 1,
  MODE_SYNFREQUENT = 2,
  MODE_LOWCONTINUOUS = 3,
  MODE_HIGHCONTINUOUS = 4
}
