//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum IKLog {
  IK_Log_STATUS = 1,
  IK_Log_VERBOSE = 2,
  IK_Log_DEBUG = 3,
  IK_Log_INFO = 4,
  IK_Log_WARN = 5,
  IK_Log_ERROR = 6,
  IK_Log_Performance = 7
}
