//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IKProcessorState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IKProcessorState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IKProcessorState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IKProcessorState obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IKProcessorState() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_IKProcessorState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public IKEnrollIdentMode mode {
    set {
      dllmainPINVOKE.IKProcessorState_mode_set(swigCPtr, (int)value);
    } 
    get {
      IKEnrollIdentMode ret = (IKEnrollIdentMode)dllmainPINVOKE.IKProcessorState_mode_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisAndFaceDataValidFlag dataValidFlag {
    set {
      dllmainPINVOKE.IKProcessorState_dataValidFlag_set(swigCPtr, (int)value);
    } 
    get {
      IKIrisAndFaceDataValidFlag ret = (IKIrisAndFaceDataValidFlag)dllmainPINVOKE.IKProcessorState_dataValidFlag_get(swigCPtr);
      return ret;
    } 
  }

  public IKIrisProcessorState pIrisState {
    set {
      dllmainPINVOKE.IKProcessorState_pIrisState_set(swigCPtr, IKIrisProcessorState.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKProcessorState_pIrisState_get(swigCPtr);
      IKIrisProcessorState ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKIrisProcessorState(cPtr, false);
      return ret;
    } 
  }

  public IKFaceProcessorState pFaceState {
    set {
      dllmainPINVOKE.IKProcessorState_pFaceState_set(swigCPtr, IKFaceProcessorState.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = dllmainPINVOKE.IKProcessorState_pFaceState_get(swigCPtr);
      IKFaceProcessorState ret = (cPtr == global::System.IntPtr.Zero) ? null : new IKFaceProcessorState(cPtr, false);
      return ret;
    } 
  }

  public IKProcessorState() : this(dllmainPINVOKE.new_IKProcessorState(), true) {
  }

}
