//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SELFRECT : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SELFRECT(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SELFRECT obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SELFRECT obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SELFRECT() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          dllmainPINVOKE.delete_SELFRECT(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int left {
    set {
      dllmainPINVOKE.SELFRECT_left_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.SELFRECT_left_get(swigCPtr);
      return ret;
    } 
  }

  public int top {
    set {
      dllmainPINVOKE.SELFRECT_top_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.SELFRECT_top_get(swigCPtr);
      return ret;
    } 
  }

  public int right {
    set {
      dllmainPINVOKE.SELFRECT_right_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.SELFRECT_right_get(swigCPtr);
      return ret;
    } 
  }

  public int bottom {
    set {
      dllmainPINVOKE.SELFRECT_bottom_set(swigCPtr, value);
    } 
    get {
      int ret = dllmainPINVOKE.SELFRECT_bottom_get(swigCPtr);
      return ret;
    } 
  }

  public SELFRECT() : this(dllmainPINVOKE.new_SELFRECT(), true) {
  }

}
